from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "apps"

urlpatterns = [
    path('diagramme-uml', views.uml, name="uml"),
    path('', views.index, name='home'),
    path("contact", views.contact, name="contact"),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('messagerie/', views.messagerie_view, name='messagerie'),
    path('covoiturage/', views.liste_voyages, name='liste-voyages'),
    path('covoiturage/<int:voyage_id>', views.voyage_single, name='voyages-single'),
    path('covoiturage/<int:voyage_id>', views.reserver_voyage, name='voyages-confirmation'),
    path('covoiturage/créer', views.creer_voyage, name='creer-voyage'), 
    path('covoiturages/', views.mes_voyages, name='mes_voyages'),
    path('voyage/<int:voyage_id>/demarrer/', views.demarrer_voyage, name='demarrer_voyage'),
    path('voyage/<int:voyage_id>/terminer/', views.terminer_voyage, name='terminer_voyage'),
    path('acheter-credits/', views.acheter_credits, name='acheter_credits'),
    path('paiement/ajouter/', views.ajouter_moyen_paiement, name='ajouter-moyen-paiement'),
    path('settings/', views.settings_view, name='settings'),
    path("connexion/", views.connexion_view, name="connexion"),
    path('inscription/', views.inscription_view, name='inscription'),
    path('deconnexion/', views.deconnexion_view, name='deconnexion'),
    path('litige/signal/', views.signaler_litige, name='signaler_litige'),
    path('staff/litiges/', views.liste_litiges, name='liste_litiges'),
    path('staff/litige/<int:litige_id>/', views.litige_detail, name='litige_detail'),
    path('staff/litiges/<int:litige_id>/supprimer/', views.supprimer_litige, name='supprimer_litige'),
    path('messagerie/litige/<int:litige_id>/', views.messagerie_view, name='voir_litige'),
    path('voyage/<int:voyage_id>/laisser-avis/', views.laisser_avis, name='laisser_avis'),
    path('get_modeles/', views.get_modeles, name='get_modeles'),
    path('véhicule/ajouter', views.ajouter_voiture, name='ajouter_voiture'),
    path('administrateur/espace/', views.espace_admin, name='espace_admin'),
    path('staff/espace/', views.espace_staff, name='espace_staff'),
    path('administrateur/creer-employe/', views.creer_employe, name='creer_employe'),
    path('administrateur/utilisateur/<int:user_id>/suspendre/', views.suspendre_utilisateur, name='suspendre_utilisateur'),
    path('administrateur/utilisateur/<int:user_id>/reactiver/', views.reactiver_utilisateur, name='reactiver_utilisateur'),
    path('staff/avis/', views.avis_liste, name='avis_liste'),
    path('staff/avis/<int:avis_id>/valider/', views.valider_avis, name='valider_avis'),
    path('staff/avis/<int:avis_id>/supprimer/', views.supprimer_avis, name='supprimer_avis'),
    path('staff/pages/', views.gestion_pages, name='gestion_pages'),
    path('staff/pages/<int:page_id>/', views.gestion_pages, name='gestion_pages'),    
    path('staff/presentation/<int:instance_id>/', views.gestion_presentation_utilisateur, name='gestion_presentation_utilisateur'),
    path('staff/presentation/', views.gestion_presentation_utilisateur, name='gestion_presentation_utilisateur'),
    path('staff/voyages/', views.liste_voyages_admin, name='liste_voyages_admin'),
    path('staff/voyage/<int:voyage_id>/', views.detail_voyage_admin, name='detail_voyage_admin'),
    path('staff/voyage/<int:voyage_id>/modifier/', views.modifier_voyage_admin, name='modifier_voyage_admin'),
    path('staff/voyage/<int:voyage_id>/supprimer/', views.supprimer_voyage_admin, name='supprimer_voyage_admin'),
    path('staff/temoignage/', views.gestion_temoignage, name='gestion_temoignage'),
    path('staff/temoignage/<int:instance_id>/', views.gestion_temoignage, name='gestion_temoignage'),
    path('staff/factures/', views.liste_factures, name='liste_factures'),
    path('staff/factures/<int:facture_id>/', views.detail_facture, name='detail_facture'),
    path('facture/<int:facture_id>/marquer-payee/', views.marquer_paye, name='marquer_paye'),
    path('factures/supprimer/<int:facture_id>/', views.supprimer_facture, name='supprimer_facture'),

    path('presentation-utilisateur/<int:pk>/json/', views.presentation_utilisateur_json, name='presentation_utilisateur_json'),
]
