# Generated by Django 5.2.1 on 2025-05-11 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('avantage_1', models.CharField(max_length=200, verbose_name='Avantage 1')),
                ('avantage_2', models.CharField(max_length=200, verbose_name='Avantage 2')),
                ('avantage_3', models.CharField(max_length=200, verbose_name='Avantage 3')),
                ('icone_avantage_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icône Avantage 1')),
                ('icone_avantage_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icône Avantage 2')),
                ('icone_avantage_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icône Avantage 3')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_conducteur', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('depart', models.CharField(max_length=100)),
                ('arrivee', models.CharField(max_length=100)),
                ('date_depart', models.DateTimeField()),
                ('places_disponibles', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='apps.voyage')),
            ],
        ),
    ]
