# Generated by Django 5.2.1 on 2025-05-11 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CB', 'Carte Bancaire'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('APPLEPAY', 'Apple Pay'), ('GOOGLEPAY', 'Google Pay'), ('AUTRE', 'Autre')], max_length=20)),
                ('nom', models.CharField(help_text='Nom sur le moyen de paiement (ex : Visa, compte PayPal...)', max_length=100)),
                ('details', models.CharField(blank=True, help_text='Détails (4 derniers chiffres, identifiant PayPal...)', max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_paiement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
