# Generated by Django 5.2.1 on 2025-05-12 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_moyenpaiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_litige', models.CharField(choices=[('voyage', 'Voyage'), ('reservation', 'Réservation')], max_length=20)),
                ('sujet', models.CharField(max_length=255)),
                ('description_initiale', models.TextField()),
                ('est_resolu', models.BooleanField(default=False)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='apps.reservation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges_envoyes', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='apps.voyage')),
            ],
        ),
    ]
