# Generated by Django 5.2.1 on 2025-05-12 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_litige'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description_avantage_1',
            field=models.CharField(default='test', max_length=200, verbose_name='Description Avantage 3'),
        ),
        migrations.AddField(
            model_name='site',
            name='description_avantage_2',
            field=models.CharField(default='test', max_length=200, verbose_name='Description Avantage 3'),
        ),
        migrations.AddField(
            model_name='site',
            name='description_avantage_3',
            field=models.CharField(default='test', max_length=200, verbose_name='Description Avantage 3'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Avis')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note (1 à 5)')),
                ('est_affiche', models.BooleanField(default=False, help_text='Afficher cet avis publiquement')),
                ],
        ),
    ]
