# Generated by Django 5.2.1 on 2025-05-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_credit_voiture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(max_length=200)),
                ('description_courte', models.CharField(max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('type_page', models.CharField(choices=[('utilisateurs', 'Présentation des utilisateurs'), ('temoignages', 'Témoignages et avantages')], max_length=20)),
                ('section_1_titre', models.CharField(max_length=200)),
                ('section_1_sous_titre', models.CharField(max_length=200)),
                ('section_1_texte', models.TextField()),
                ('section_1_image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
                ('section_2_titre', models.CharField(max_length=200)),
                ('section_2_sous_titre', models.CharField(max_length=200)),
                ('section_2_texte', models.TextField()),
                ('section_2_image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
                ('section_3_titre', models.CharField(max_length=200)),
                ('section_3_sous_titre', models.CharField(max_length=200)),
                ('section_3_texte', models.TextField()),
                ('section_3_image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(max_length=200)),
                ('description_courte', models.CharField(max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='presentations/')),
                ('miniature_image', models.ImageField(blank=True, null=True, upload_to='presentations/miniatures/')),
                ('raison_1_titre', models.CharField(max_length=200)),
                ('raison_1_description', models.TextField()),
                ('raison_1_icone', models.CharField(blank=True, max_length=100, null=True)),
                ('raison_1_image', models.ImageField(blank=True, null=True, upload_to='presentations/raisons/')),
                ('raison_2_titre', models.CharField(max_length=200)),
                ('raison_2_description', models.TextField()),
                ('raison_2_icone', models.CharField(blank=True, max_length=100, null=True)),
                ('raison_2_image', models.ImageField(blank=True, null=True, upload_to='presentations/raisons/')),
                ('raison_3_titre', models.CharField(max_length=200)),
                ('raison_3_description', models.TextField()),
                ('raison_3_icone', models.CharField(blank=True, max_length=100, null=True)),
                ('raison_3_image', models.ImageField(blank=True, null=True, upload_to='presentations/raisons/')),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('sous_titre', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('temoignage_1_titre', models.CharField(max_length=200)),
                ('temoignage_1_sous_titre', models.CharField(max_length=200)),
                ('temoignage_1_texte', models.TextField()),
                ('temoignage_1_image', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('temoignage_2_titre', models.CharField(max_length=200)),
                ('temoignage_2_sous_titre', models.CharField(max_length=200)),
                ('temoignage_2_texte', models.TextField()),
                ('temoignage_2_image', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('temoignage_3_titre', models.CharField(max_length=200)),
                ('temoignage_3_sous_titre', models.CharField(max_length=200)),
                ('temoignage_3_texte', models.TextField()),
                ('temoignage_3_image', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='cover_text',
            field=models.CharField(default='test', max_length=200, verbose_name='cover text'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facture', models.CharField(choices=[('entretien', 'Entretien'), ('assurance', 'Assurance'), ('carburant', 'Carburant'), ('peage', 'Péage'), ('commission', 'Commission Covoiturage'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='apps.voiture')),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='apps.voyage')),
            ],
        ),
    ]
