# Generated by Django 5.2.1 on 2025-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_presentationutilisateur_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
