# Generated by Django 5.2.1 on 2025-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_profilutilisateur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='photo_profil_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
