# Generated by Django 5.2.1 on 2025-05-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_avi_delete_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_facture',
            field=models.CharField(choices=[('achat_credit', 'Achat de crédits'), ('100€ carburant', '100€ carburant'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='voiture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='apps.voiture'),
        ),
    ]
