# Generated by Django 5.2.1 on 2025-05-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_facture_type_facture_alter_facture_voiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='ecologique',
            field=models.BooleanField(default=False),
        ),
    ]
