# Generated by Django 5.2.1 on 2025-05-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_voyage_ecologique'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='etat',
            field=models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_VENIR', max_length=20),
        ),
    ]
