# Generated by Django 5.2.1 on 2025-05-23 02:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_voyage_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='litige',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apps.litige'),
        ),
    ]
