# Generated by Django 5.2.1 on 2025-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_message_date_envoi_message_litige'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='est_utilisateur',
            field=models.BooleanField(default=True),
        ),
    ]
