# Generated by Django 5.2.1 on 2025-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_profilutilisateur_est_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
    ]
